spring:
  application:
    name: kafka-windowing-demo
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
    streams:
      application-id: kafka-windowing-demo
      properties:
        state.dir: ./build/tmp/state-dir
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: xiaoyf.demo.kafka.windowing.serde.CountingSerde
        processing.guarantee: exactly_once_v2

kafka-windowing:
  measurement-topic: measurement
  aggregated-measurements-topic: aggregated_measurements
  window-size: PT5M
  grace: PT0M

logging:
  level:
    root: INFO
